### ISSUE TITLE
fatal: could not read from remote repository 

### ISSUE THREAD

**Issue by pgrwe** [nmfisher/thermion_examples#1]
Resolving dependencies in `<filepathto\cli_dummy>`... (1.5s)
Git error. Command: `git clone --mirror git@github.com:nmfisher/thermion_windows_fix.git`

Seems like lines 10-14 in pubspec.yaml can be omitted? 
```
dependencies:
  thermion_dart: 
    git:
      url: git@github.com:nmfisher/thermion_windows_fix.git
      path: thermion_dart
```
